### ISSUE TITLE
ImportError: No module named Config

### ISSUE THREAD

**Issue by 12DReflections** [pierrebaque/EM#1]
There is no Config module so this error keeps showing when trying to run.

`Traceback (most recent call last):
  File "EM.py", line 36, in <module>
    from pom_room import POM_room
  File "/py/DeepOcclusion-master/pom_room.py", line 9, in <module>
    import Config`

**Comment by pierrebaque** [comment]
Hello @12DReflections ,

I updated the README file with instructions to run and a link to download a folder containing everything you need to run the demo, among which a valid Config file.

Please let me know about any other issue.
