### ISSUE TITLE
No such file or directory: '/cvlabdata1/cvlab/datasets_people_tracking/ETH/day_2/annotation_final/cvlab_camera2/begin/00000100.png

### ISSUE THREAD

**Issue by li10141110** [pierrebaque/EM#10]
please help,i can't find it.

**Comment by li10141110** [comment]
**** @pierrebaque my bro,did I missed the cvlabdata,but I have downloaded tozip.Please help me.thank you for your time!

**Comment by pierrebaque** [comment]
In which file did you find this reference?
 It should not be here and you should change the path to whatever image you want to use.

**Comment by li10141110** [comment]
OK,i get it.
but unfornturely, when i run RunPom.py i get this error:

Saved file : ./results/res_nounaries_a2.500000_p230.000000_ablack1.500000/00002870.dat
Saved file : ./results/res_nounaries_a2.500000_p230.000000_ablack1.500000/00002840.dat
Saved file : ./results/res_nounaries_a2.500000_p230.000000_ablack1.500000/00002820.dat
Saved file : ./results/res_nounaries_a2.500000_p230.000000_ablack1.500000/00002830.dat
Saved file : ./results/res_nounaries_a2.500000_p230.000000_ablack1.500000/00002970.dat
Saved file : ./results/res_nounaries_a2.500000_p230.000000_ablack1.500000/00002800.dat
Traceback (most recent call last):
  File "/home/lijing/Desktop/shendu/DeepOcclusion/RunPom.py", line 179, in <module>
    Parallel(n_jobs=n_threads)(delayed(runsave)(fid) for fid in fids)
  File "/home/lijing/Envs/tf0.12/lib/python2.7/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/lijing/Envs/tf0.12/lib/python2.7/site-packages/joblib/parallel.py", line 740, in retrieve
    raise exception
joblib.my_exceptions.JoblibIndexError: JoblibIndexError
___________________________________________________________________________
Multiprocessing exception:
...........................................................................
/home/lijing/Desktop/shendu/DeepOcclusion/RunPom.py in <module>()
    174 
    175 n_threads =40
    176 
    177 for block in range(0,len(room.img_index_list)/n_threads+1):
    178     fids = range(n_threads*block,n_threads*(block+1))
--> 179     Parallel(n_jobs=n_threads)(delayed(runsave)(fid) for fid in fids)
    180 
    181 
    182 # ### Test
    183 

...........................................................................
/home/lijing/Envs/tf0.12/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=40), iterable=<generator object <genexpr>>)
    784             if pre_dispatch == "all" or n_jobs == 1:
    785                 # The iterable was consumed all at once by the above for loop.
    786                 # No need to wait for async callbacks to trigger to
    787                 # consumption.
    788                 self._iterating = False
--> 789             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=40)>
    790             # Make sure that we get a last message telling us we are done
    791             elapsed_time = time.time() - self._start_time
    792             self._print('Done %3i out of %3i | elapsed: %s finished',
    793                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Sub-process traceback:
---------------------------------------------------------------------------
IndexError                                         Mon Sep 18 16:00:51 2017
PID: 152701              Python 2.7.13: /home/lijing/Envs/tf0.12/bin/python
...........................................................................
/home/lijing/Envs/tf0.12/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function runsave>
        args = (100,)
        kwargs = {}
        self.items = [(<function runsave>, (100,), {})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/lijing/Desktop/shendu/DeepOcclusion/RunPom.py in runsave(fid=100)
    166 if not os.path.exists(folder_out):
    167     os.makedirs(folder_out)
    168    
    169 
    170 def runsave(fid):
--> 171     Q_out = POMLauncher.run_NMS(fid,room,rad = radius,thresh_p  = thresh)
        Q_out = undefined
        fid = 100
    172     room.save_dat(Q_out,fid,folder_out)
    173     
    174 
    175 n_threads =40

...........................................................................
/home/lijing/Desktop/shendu/DeepOcclusion/POMLayers1.py in run_NMS(self=<POMLayers1.pomLayer instance>, fid=100, room=<pom_room.POM_room object>, rad=4, thresh_p=0.05)
    477     def run_NMS(self,fid,room,rad = 7,thresh_p  = 0.8):
    478     #Load image into tensor
    479 
    480         #set priors
    481         #load unaries
--> 482         unaries_logp = np.load(self.unaries_path%room.img_index_list[fid])
        unaries_logp = undefined
        self.unaries_path = './Potentials/Unaries/RunFeatures_transfer/%08d.npy'
        room.img_index_list = [2000, 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100, 2110, 2120, 2130, 2140, 2150, 2160, 2170, 2180, 2190, ...]
        fid = 100
    483         unaries_logp = unaries_logp.clip(np.log(0.2),1000)
    484         unaries_logp_max = np.max(unaries_logp,axis = 0)
    485         #process them
    486         unaries = unaries_logp_max.reshape((room.H_grid,room.W_grid))

IndexError: list index out of range
___________________________________________________________________________

Process finished with exit code 1

here the /home/lijing/Desktop/shendu/DeepOcclusion/results/res_NMS_t0.050000_rad4.000000/00002000.dat
the contents is:
0 0.200000
1 0.000000
2 0.000000
3 0.000000
4 0.200000
5 0.000000
6 0.000000
7 0.000000
8 0.200000
9 0.000000
10 0.000000
11 0.000000
12 0.200000
13 0.000000
14 0.000000
````````


So mannnnnny, am'I get the right result? thank you very much for your time!May you a good day!
