### ISSUE TITLE
Whats about algorithm's speed?

### ISSUE THREAD

**Issue by seovchinnikov** [pierrebaque/EM#12]
Hello!
Thank you for your work!
I have a question about algo perfomance that I was not able to find in the paper, what are the numbers in general, what are the heaviest parts in the online step, and how does it depend on GPU perfomance?

**Comment by pierrebaque** [comment]
Hello @seovchinnikov ,

At run time, the heaviest part is definitely the Mean-Field inference part, but it runs on cpu, so if you have many cores, it can go fast.
The main reason for Mean-Field inference part to run on CPU, is that it makes heavy use of "cumsum" kind of operations, which are faster on CPU according to theano documentation.

In practice, the runting time really depends on your image resolution and number of cameras. If you work with large images and 7 cameras, as I did with this dataset, (https://cvlab.epfl.ch/data/wildtrack), it will be several seconds long on one CPU.

However, you can easily downsample the images or the activation maps (i.e. the ones which are fed to the Mean-Fields inference loop) to get a good speedup. It will then run below 1 second.

I hope this answers your question.

Let me know if you have any issue.

Best,
Pierre

**Comment by filipetrocadoferreira** [comment]
How does your python version of POM compares to the c++ (original) version? I tried to implement in python with multiprocessing but I never got faster than original c++ code

**Comment by pierrebaque** [comment]
If you don't use part based higher-order potentials and only the segmentation based ones, my implementation should be faster that vanilla POM (c++ (original) version). It uses Theano fast operations on matrices, while still using the integral image method.
If you happen to do some quantitative comparisons, I would be very interested to know.

Best
Pierre

**Comment by filipetrocadoferreira** [comment]
I was using numpy's cumsum to calculate integral images. It was the main bottleneck. My python version was 2-5x slower.
