### ISSUE TITLE
Training Code?

### ISSUE THREAD

**Issue by filipetrocadoferreira** [pierrebaque/EM#13]
Hi! congratz for the great work.

Are you planning to share training code? I'm not able to reproduce results using current code because of old theano/cuda dependencies.

**Comment by pierrebaque** [comment]
Hello,

Thanks for your message.
Yes, we have a student who is working on an improved training on COCO dataset. She will release her code here afterwards.

What kind of old dependencies? Theano use CuDNN 5.8, if you have the newer version (6.0) installed, it will not work. I think that no distribution of Theano uses 6.0

Cheers

**Comment by filipetrocadoferreira** [comment]
Good to hear that! Thank you for your disponibility.

**Comment by filipetrocadoferreira** [comment]
Any plans for Release?

**Comment by pierrebaque** [comment]
Hello,
Thanks for your interest.

Yes, @gooa1121  is currently testing the newly trained weights  on several datasets, and it shouldn't take long. Release will be done quickly.

Best wishes,
Pierre

**Comment by filipetrocadoferreira** [comment]
That's awesome. I think your work really inspiring! Looking forward to the new implementation.
