### ISSUE TITLE
ImportError: cannot import name as_cuda_ndarray_variable

### ISSUE THREAD

**Issue by hjjlovecyy** [pierrebaque/EM#15]
When i run RunUnaries.ipynb, this error occurred. So i find some answer in google. Someone said that upgrade the Theano , and it did work, but another error occur and the terminal suggest us to browse https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29. It says something about cuda, but mac needs cuda? it trouble me a lot. How can i solve this problem —— ImportError: cannot import name as_cuda_ndarray_variable.
Thanks

**Comment by pierrebaque** [comment]
Hello,

I cannot help you for library related problems. The code is written to be ran with GPU backend. This being said, I think that you can modify it to run on cpu only.

Best
