### ISSUE TITLE
Header file format of ".pom" file

### ISSUE THREAD

**Issue by yurinishikawa** [pierrebaque/EM#16]
Hi, thanks for sharing your great work!

I downloaded a ZIP file from Google Drive, and was able to run the .ipynb codes successfully.
However, I am a bit confused.

The header section of "rectangles80x80.pom" is:

  ROOM 80 80 4 1600

I suppose the "ROOM" header means 
img_width = 80, img_height = 80, number of cameras = 4, number of locations = 1600 according to [1] and [2]

 [1] https://cvlab.epfl.ch/software/pom
 [2] https://github.com/pierrebaque/generatePOMfile

However, there seem to be 6400 locations as long as I looked at subsequent "RECTANGLES" sections of "rectangles80x80.pom"
Which is the correct number of locations,  6400(=80x80??) or 1600?  

Plans to fix this in the future?

**Comment by hjjlovecyy** [comment]
Hi, i want to know what system are you used?
I can't run the .ipynb 
i use macos
can you solve this problem?
thanks!

**Comment by pierrebaque** [comment]
Hello,

There may be a mistake in the ROOM header of this rectangles80x80.pom file. 
There are indeed 6400 locations and the header is only here for informative purposes, it is not used in the code.

Cheers
Pierre

**Comment by yurinishikawa** [comment]
Pierre, 
Thank you for your kind reply!

Best,
Yuri
