### ISSUE TITLE
The Result

### ISSUE THREAD

**Issue by hjjlovecyy** [pierrebaque/EM#17]
Hi, thank for your great work!
it seem that i run this project without error, but it blocks on the RunPom file(multithread model).
Am I wrong? And what is the result of this project
thanks

**Comment by pierrebaque** [comment]
Hello,

Can you give more details on what blocks you please?

Thanks
Pierre

**Comment by hjjlovecyy** [comment]
`from joblib import Parallel, delayed
import multiprocessing

n_threads =40

for block in range(0,len(room.img_index_list)/n_threads+1):
    fids = range(n_threads*block,n_threads*(block+1))
    Parallel(n_jobs=n_threads)(delayed(runsave)(fid) for fid in fids)`

it blocks here a long time, and has no output.

Thanks
@pierrebaque
