### ISSUE TITLE
ImportError: No module named roi_pooling

### ISSUE THREAD

**Issue by cxplanet** [pierrebaque/EM#2]
When running the Unaries notebook, it has a dependency on what I believe is https://github.com/ddtm/theano-roi-pooling. It would be good to capture that in the readme.

There are also a number of imports referencing theano.tensor.signal.downsample in the codebase which is no longer available in current release 0.9 of theano. There's no code that actually uses the import, but it does stop the notebooks from running. I can make a pull request for those if needed.

**Comment by pierrebaque** [comment]
Thanks for reminding me of the dependency on ROIPooling.
I also removed the reference to theano.tensor.signal.downsample

Thanks for your collaboration, very helpful!
