### ISSUE TITLE
Config missing

### ISSUE THREAD

**Issue by lesonkorenac** [pierrebaque/EM#28]
I tried to run first notebook RunParts.ipynb.
After I figured out that I need to use theano 0.9 and python 2.7 I've got stuck on missing import Config.
I tried to create it on my own, but I don't know what it's content should be.

**Comment by gooa1121** [comment]
Hi,
I added it back. Thanks for reporting it.

**Comment by lesonkorenac** [comment]
Thank you. I realized it was my mistake. Config.py is in the provided tozip.zip archive.
