### ISSUE TITLE
Missing gaussian_params.txt

### ISSUE THREAD

**Issue by cxplanet** [pierrebaque/EM#3]
When I run the RunPom notebook, it expects to find a gaussian params file.

IOError: [Errno 2] No such file or directory: './Potentials/Parts/Run_transfer/gaussian_params.txt'

**Comment by pierrebaque** [comment]
Hello @cxplanet,

Did you run the notebook called "RunParts.ipynb" first? It should create this file. 

Let me know.
Cheers,
Pierre

**Comment by liushaoqian** [comment]
5    "execution_count": 1,
      6    "metadata": {
----> 7     "collapsed": false,
      8     "deletable": true,
      9     "editable": true

NameError: name 'false' is not defined

I just want to know why false is not defined,and I changed the lower f to greater F,but it still error

**Comment by pierrebaque** [comment]
Hello,

What is this file?
