### ISSUE TITLE
Error run ./RunParts.ipynb   -- end of file unexpected

### ISSUE THREAD

**Issue by GehenHe** [pierrebaque/EM#30]
As I run with `./RunParts.ipynb` in the root directory
I got this error

> ./RunParts.ipynb: 1739: ./RunParts.ipynb: Syntax error: end of file unexpected (expecting "}")

What may cause this problem?

**Comment by gooa1121** [comment]
Hi, did you use Jupyter Notebook to run this file?

**Comment by GehenHe** [comment]
Oh,that's my fault. I'll try this whether it can be run correctly
