### ISSUE TITLE
ImportError: No module named Config

### ISSUE THREAD

**Issue by guiyuliu** [pierrebaque/EM#6]
when I run  Runparts.ipynb , this error occurred. I think "Config" is a configuration file , but I can't find this file 
could you please help me ?
thanks !

**Comment by guiyuliu** [comment]
```
DeepOcclusion/pom_room.py in <module>()
      7 import random
      8 
----> 9 import Config
     10 class POM_room(object):
ImportError: No module named Config
```

**Comment by pierrebaque** [comment]
Hello @guiyuliu ,
You need to follow the instructions in the README.txt and download the zip file containing the example to run. You will find a Config.py file inside, which is the one you want to import.

Best,
Pierre
