### ISSUE TITLE
What does the 'Part' mean?

### ISSUE THREAD

**Issue by lc-git** [pierrebaque/EM#7]
Hi pierrebaque,

I am confused with the 'parts' in the RunParts.ipynb, what does the 'parts' mean? and what does the RunParts.ipynb do? Why there are 9 parts? Thank you for your time.

**Comment by pierrebaque** [comment]
Hello @lc-git,
As you can read in the paper, there is a pre-defined number of Gaussians which can be set as a meta-parameter. These Gaussians intuitively correspond to "body parts", which have been discovered and learned by the CNN.

At run time (i.e. when we do actual detection), for each image we run the parts discriminating network, which will give the probability for each pixel to belong to a given part ( which correspond to mode weights from the gaussian mixture), and sample from it. These predictions are then used for actual detections.

Best,
Pierre

**Comment by lc-git** [comment]
Hi @pierrebaque,
Thank you for your help. I set up all the configs and environment following README. The result of 'run_pom' function is Q_out, whose element is 1 or 0. I  wonder whether the result I got is correct or not. I mean I thought the result would be probability, float number like 0.9, 0.8, 0.1 but it is binary. So I just want to double check. Thank you.
