### ISSUE TITLE
The result of pom, Q_out

### ISSUE THREAD

**Issue by lc-git** [pierrebaque/EM#8]
Hi @pierrebaque,
Thank you for your help. I set up all the configs and environment following README. The result of 'run_pom' function is Q_out, whose element is 1 or 0. I wonder whether the result I got is correct or not. I mean I thought the result would be probability, float number like 0.9, 0.8, 0.1 but it is binary. So I just want to double check. Thank you.

**Comment by pierrebaque** [comment]
Hi @lc-git ,

It should be float number indeed. Depending on the confidence and on the temperature, they can be really close to 0 or 1. If you use "run_pom" with T_0 = large (>100.0) for instance, you should definitely get float numbers.

Cheers
Pierre
