### ISSUE TITLE
which encoding is needed to load the model parameter?

### ISSUE THREAD

**Issue by tuobay** [pierrebaque/EM#9]
Hi,
When I run the demo, I come across a problem,::::::
  File ".\DeepOcclusion\DeepOcclusion\VGG\VGGNet.py", line 98, in __init__
    paramsValuesVGG = pickle.load(open(os.path.dirname(__file__)+"/models/paramsVGG.pickle","rb"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

It seems encoding is wrong, which should I use? 

Thanks?

**Comment by tuobay** [comment]
I am using Windows platform.

**Comment by nuptwuchen** [comment]
做数模的看过来

**Comment by tuobay** [comment]
你们这题做的怎么样？

**Comment by nuptwuchen** [comment]
卡住了，不会python。想找个matlab的，找不到

**Comment by pierrebaque** [comment]
Is the problem solved?
Could you please try to use English so that everybody can understand?

Thanks

**Comment by nuptwuchen** [comment]
hello, i am a student.
I'm attending a gam which  ask me for realistic multi-camera foreground extraction.
here is the question.
How can I effectively detect and extract video foreground goals through multiple surveillance videos (see Figure 3) that are similar to the same location taken at different angles? Please take full account of and use the correlation information between multiple perspectives (or between backgrounds)

this is the forth question and i have finished the  first three questions by matlab. However, i am not familiy with python. if u can help me, i will say 
while(true){
  console.log('3q');
}

**Comment by pierrebaque** [comment]
Hello,
Good luck with your course then.

Best wishes,
Pierre
